### PR TITLE
Changed morse code letter spacing

### PR DESCRIPTION
**Pull request by JimZAH**
Changed interlettertime from 4 -> 3. Sounds more natural.

### CODE REVIEW

**Comment by KG7QIN** [comment]
Thanks for the change.  

It is missing DCO.  Please fix.

```
DCO

You only have one commit incorrectly signed off! To fix, head to your local branch and run:

git commit --amend --signoff

Now your commits will have your sign off. Next run

git push --force-with-lease origin patch-1

Commit sha: 828417a, Author: JimZAH, Committer: GitHub; The sign-off is missing.
```

**Comment by KG7QIN** [comment]
Looking at this change, I'm wondering it this would be a good addition to the [globals] section of app_rpt, adding this in as one of the variables/settings available?  You could then make this change both in the rpt.conf file as well as at run time via the CLI.

**Comment by JimZAH** [comment]
> Thanks for the change.
> 
> It is missing DCO. Please fix.
> 
> ```
> DCO
> 
> You only have one commit incorrectly signed off! To fix, head to your local branch and run:
> 
> git commit --amend --signoff
> 
> Now your commits will have your sign off. Next run
> 
> git push --force-with-lease origin patch-1
> 
> Commit sha: 828417a, Author: JimZAH, Committer: GitHub; The sign-off is missing.
> ```

Sorry, will give that a go. I'm new to signing off commits!

**Comment by JimZAH** [comment]
> Looking at this change, I'm wondering it this would be a good addition to the [globals] section of app_rpt, adding this in as one of the variables/settings available? You could then make this change both in the rpt.conf file as well as at run time via the CLI.

I agree, maybe a variable called farnsworth? 

I'll adjust the give it a test at home and submit

**Comment by JimZAH** [comment]
Will close this request and re-open with farnsworth variable.

**Pull request closed without merging**
