### PR TITLE
Added comments to app_rpt.c

### PR DESCRIPTION
**Pull request by KG7QIN**
Having attempted to port the app_rpt.c and other modules to Asterisk 1.8, I've been asked if I can contribute by adding comments/documentation to the source code of the various modules.

This is the start of that process.  So far, I've only made my way through half of the app_rpt.c, and then that is only to start adding in comments at the beginning of the various functions it has.  

Once I finish with this part, I will attempt to go back into the various functions and see if I can add comments on what everything is doing.

### CODE REVIEW

**Comment by N4IRS** [comment]
Stacey,
Thanks for the comments added to app_rpt.c I have 2 comments. Please make your pull requests against the develop branch. On line 715 of your pull request, you have a change to the code itself. We prefer changes stay within the scope of pull request description. This makes code review and merge easier.

Thanks, Steve

**Comment by MrBungle42** [comment]
The code change was because Stacey did not merge with the current version of app_rpt.c  Steve changed the code in commit: 47426d0f0ef81a5c7d181424f5bf0526a353b47a.

**Comment by KG7QIN** [comment]
Hmm, looks like I may have pulled this from your repository or one of the other directories.  Interesting.  I will remove the change and do a new commit.

**Comment by KG7QIN** [comment]
I'm going to close this and make the changes on my end and resubmit.

**Comment by KG7QIN** [comment]
Ok, I've moved this as a new pull request against the app_rpt.c in the develop branch. 

The CR/LFs in the file there initially made git think the whole file changed, until I did a:
git config --global core.autocrlf input

(Note I'm on an ubuntu box :)

**Pull request closed without merging**
