### PR TITLE
Allow users to adjust morse code letter spacing

### PR DESCRIPTION
**Pull request by JimZAH**
This is the same PR as #57 however, no white space has been removed. Sorry about that.

### CODE REVIEW

**Comment by TheCranston** [comment]
JimZAH, code looks good.  thanks for removing the white space changes.  Please resolve the DCO check and we can move forward with approving the PR.

**Comment by JimZAH** [comment]
@TheCranston Sorry, I'm having a real hard time with DCO. I have no idea why. Follow the documentation doesn't seem to yield desirable results. I'm still trying, very new to this.

**Comment by TheCranston** [comment]
Jim, just click on the "details" next to the DCO line and it will give you two commands to run from your local copy.  that should get you there.

**Comment by JimZAH** [comment]
@TheCranston Thank you, I have done that but it doesn't seem to work. I just end up increasing my commit count :-(. I clearly need a more git exposure. Sorry for mucking you about, I'm afraid I seem to be stuck!

**Comment by w0jrl** [comment]
If you're pushing from the commandline, run:
git commit --amend --signoff
Then run:
git push --force-with-lease
You may want to rebase first though.

**Comment by w0jrl** [comment]
It looks like commit fdb45fd002b30a54696dae7cda728a8a679e7312 needs to be signed.
You can do it by running:
git rebase -i fdb45fd002b30a54696dae7cda728a8a679e7312
In the editor that appears, replace 'pick' with 'edit'.
Then run:
git commit --amend --signoff --no-edit
git rebase --continue
git push --force-with-lease

**Review by TheCranston — APPROVED** [review]
Code looks good.  Thanks for the submission!

**Comment by JimZAH** [comment]
@w0jrl Thank you for assisting, sorry for all the trouble. I've now managed to sign commit fdb45fd. Thank you to both of you for your patience.

**Review by w0jrl — APPROVED** [review]

**Comment by TheCranston** [comment]
Jim,
Did you sign that PR with your local GPG keys?

**Comment by JimZAH** [comment]
@TheCranston No, I've just uploaded my GPG Key block to my account. Now RTFM to understand how to sign the PR, as before sorry for this. Not used to signing commits as normally my commits are internal...

**Comment by JimZAH** [comment]
@TheCranston It looks like the checks passed for the last commit? Am I missing something, I'm very sorry for all these problems. I thought it would be simple to post code improvements.

Sadly I've ran out of time this evening, I'll try to get back to this soon. Would really like to get these changes implemented soon.

**Comment by JimZAH** [comment]
Should I create a new PR from scratch and attempt sign correctly?

**Comment by w0jrl** [comment]
@JimZAH I think that GitHub is just stuck. I wonder if @KG7QIN can get it fixed.
The same thing happened to one of my commits for txoffdelay.

**Comment by JimZAH** [comment]
@w0jrl Thanks Jeremy, I'll stand by.

**Comment by KG7QIN** [comment]
I merged the PR in.

Thanks for the submission.   We only ask that next time you please make sure all you PRs are signed to ensure no issues arise with the review.

Thanks

**Pull request merged**
